spring:
  application:
    name: post-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/post_service"
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 60MB
  config:
    import: "optional:configserver:http://localhost:8071/"