spring:
  application:
    name: "media-service"
  config:
    import: "optional:configserver:http://localhost:8071/"

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: DEBUG

error:
  code: 2000
